apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betaserver
  template:
    metadata:
      labels:
        app: betaserver 
    spec:
      containers:
      - name: api-server
        image: singhpratyush/flask-cpu-server:latest
